using UnityEngine;

namespace Game.Characters.CapabilitySystem
{
    /*
     * We can use a shared dictionary to pass around to every file our characters important shared data
     */
    public static class CapabilityKeys
    {
        // State
        public const int IsGrounded = 100;
        public const int IsCrouching = 101;
        public const int IsSliding = 102;
        public const int IsFlying = 103;
        public const int IsSprinting = 104;
        
        // Info?
        public const int CurrentVelocityXZ = 200;
        public const int CurrentVelocityY = 201;
        
        // Stats
        public const int CurrentHealth = 301;
        public const int CurrentSpeed = 302;

    }

    /*
     * Parts generated by AI because I'm lazy, this class is an extensions class which helps with type conversion
     */
    public static class CapabilityKeyHelper
    {
        public static int FloatAsInt(this float value)
        {
            return Mathf.RoundToInt(value * 1000f);
        }
        
        public static float IntAsFloat(this int value)
        {
            return value / 1000f;
        }
        
        // Bool helpers
        public static int BoolAsInt(this bool value)
        {
            return value ? 1 : 0;
        }
        
        public static bool IntAsBool(this int value)
        {
            return value > 0;
        }
    }
    
    
}